<a href="https://colab.research.google.com/github/Rusick0/AI_Practice/blob/main/AI2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
 pip install numpy
Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:
 import numpy as np
Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:
ndarray.ndim - число измерений (чаще их называют "оси") массива.
ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html

1.2.1 Пример

In [4]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]

1.2.2 Пример

In [ ]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5 5 5 5 5 5 5 5 5 5]
 [10 11 12 13 14 15 16 17 18 19]

1.2.3 Пример

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0054054784487168606 0.9557606388825332 0.49448054054296375

1.2.4 Пример

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

1.2.5 Пример

In [ ]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False

1.2.6 Пример

In [ ]:
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]

1.3.1 Задание

In [5]:
# 1.3.1 Задание
# Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.
import numpy as np
Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

1.3.2 Задание

In [6]:
# 1.3.2 Задание
# Создать 5x5 матрицу со значениями в строках от 0 до 4.
# Для создания необходимо использовать функцию arrange.
import numpy as np
Z = np.zeros((5,5), dtype = int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

1.3.3 Задание

In [7]:
# 1.3.3 Задание
# Создать массив 3x3x3 со случайными значениями.
import numpy as np
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.13069428 0.79058734 0.84290809]
  [0.10214334 0.13067977 0.6583201 ]
  [0.26214922 0.87493013 0.09564667]]

 [[0.87679299 0.2654326  0.25634399]
  [0.39773883 0.15417828 0.12888431]
  [0.67696322 0.83792147 0.35472051]]

 [[0.66661441 0.25675849 0.90616362]
  [0.07109461 0.40899377 0.14144968]
  [0.70252864 0.5382172  0.18732728]]]

1.3.4 Задание

In [8]:
# 1.3.4 Задание
# Создать матрицу с 0 внутри, и 1 на границах.
import numpy as np
Z = np.ones((5,5), dtype=int)
Z[1:-1:,1:-1:] = 0
print(Z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

1.3.5 Задание

In [9]:
# 1.3.5 Задание
# Создать массив и отсортировать его в порядке убывания.
import numpy as np
Z = np.array(range(14))
Z.sort()
Z = Z[::-1]
print(Z)

[13 12 11 10  9  8  7  6  5  4  3  2  1  0]

1.3.6 Задание

In [10]:
# 1.3.6 Задание
# Создать матрицу 5x5 со случайными значениями.
# Вывести форму, размер и размерность матрицы.
import numpy as np
Z = np.random.random((5,5))
print("Форма матрицы:")
print(Z.shape)
print("Размер матрицы:")
print(Z.size)
print("Размерность матрицы:")
print(Z.ndim)

Форма матрицы:
(5, 5)
Размер матрицы:
25
Размерность матрицы:
2

2.1. Теоретический материал – Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких
источников.
Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:
 pip install pandas
Для импорта библиотеки используйте команду:
import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.

2.2.1 Пример

In [ ]:
import pandas as pd
lst = [1,2,3,4,5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32

2.2.2 Пример

In [ ]:
s1 = pd.Series([1,2,3,4,5], ['a','b', 'c', 'd', 'e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64

2.2.3 Пример

In [ ]:
dataFrame = pd.DataFrame()
dataFrame['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataFrame['Возраст'] = [38,25]
dataFrame['Водитель'] = [True, False]
dataFrame

                Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Пример

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataFrame = pd.read_csv(url)
dataFrame.head(5)

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0

2.2.5 Пример

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataFrame = pd.read_csv(url)
dataFrame.head(2)
dataFrame.tail(3)
dataFrame.shape
dataFrame.describe()

              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

2.2.6 Пример

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataFrame = pd.read_csv(url)

dataFrame.iloc[1:4]

,Name,PClass,Age,Sex,Survived,SexCode
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.0,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1

2.2.7 Пример

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataFrame = pd.read_csv(url)

dataFrame[dataFrame['PClass'] == '1st'].head(2)

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

2.3.1 Задание

In [11]:
# 2.3.1 Задание
# Задайте два Series, представляющих две точки в n-мерном пространстве.
# Найдите расстояние между ними.
import pandas as pd

print(sum((pd.Series([1, 2, 3, 4])-pd.Series([5, 6, 7, 8]))**2)**.5)

8.0

2.3.2 Задание

In [12]:
# 2.3.2 Задание
# Найдите в интернете любой csv файл и загрузите его в DataFrame.
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"

dataframe = pd.read_csv(url)
dataframe.head(5)

   year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

2.3.3 Задание

In [13]:
# 2.3.3 Задание
# Проделайте с получившимся из задания 2.3.2 DataFrame те же действия,
# что и в примерах 2.2.5-2.2.7.
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"

#Как в 2.2.5
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

#Как в 2.2.6
dataframe.iloc[1:4]

#Как в 2.2.7
dataframe[dataframe['name'] == 'Jennifer'].head(2)

       year      name gender  count
25     2000  Jennifer      F   9386
20489  2000  Jennifer      M     32

3.1. Теоретический материал – Работа с числовыми данными
Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).
Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.
На практике наиболее распространены следующие методы
нормализации признаков:
 Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
 Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.
При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

3.2.1 Пример

In [ ]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

minmax_scale = preprocessing.MinMaxScaler(feature_range= (0,1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2 Пример

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

scaler = preprocessing.StandardScaler()

standardized = scaler.fit_transform(x)

print(standardized)
print("Среднее: ", round(standardized.mean()))
print("Стандартное отклонение: ", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее:  0
Стандартное отклонение:  1.0

3.2.3 Пример

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                         'B':[103.02,107.26,110.35,114.23,114.68],
                         'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

          A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задание

In [14]:
# 3.3.2 Задание
# Загрузить фрейм данных Iris.
# Выполните нормализацию первого признака (sepal_length_cm) с помощью MinMaxScaler
# и второго признака (sepal_width_cm) с помощью StandardScaler.
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)


scalerM = MinMaxScaler()
dataframe[['sepal_length_cm']] = scalerM.fit_transform(dataframe[['sepal_length_cm']])


scalerZ = StandardScaler()
dataframe[['sepal_width_cm']] = scalerZ.fit_transform(dataframe[['sepal_width_cm']])

dataframe

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,0.222222,1.032057,1.4,0.2,setosa
1,0.166667,-0.124958,1.4,0.2,setosa
2,0.111111,0.337848,1.3,0.2,setosa
3,0.083333,0.106445,1.5,0.2,setosa
4,0.194444,1.263460,1.4,0.2,setosa
...,...,...,...,...,...
145,0.666667,-0.124958,5.2,2.3,virginica
146,0.555556,-1.281972,5.0,1.9,virginica
147,0.611111,-0.124958,5.2,2.0,virginica
148,0.527778,0.800654,5.4,2.3,virginica
149,0.444444,-0.124958,5.1,1.8,virginica