In [5]:
# 1.3.1 Задание
# Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.
import numpy as np
Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

In [6]:
# 1.3.2 Задание
# Создать 5x5 матрицу со значениями в строках от 0 до 4.
# Для создания необходимо использовать функцию arrange.
import numpy as np
Z = np.zeros((5,5), dtype = int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

In [7]:
# 1.3.3 Задание
# Создать массив 3x3x3 со случайными значениями.
import numpy as np
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.13069428 0.79058734 0.84290809]
  [0.10214334 0.13067977 0.6583201 ]
  [0.26214922 0.87493013 0.09564667]]

 [[0.87679299 0.2654326  0.25634399]
  [0.39773883 0.15417828 0.12888431]
  [0.67696322 0.83792147 0.35472051]]

 [[0.66661441 0.25675849 0.90616362]
  [0.07109461 0.40899377 0.14144968]
  [0.70252864 0.5382172  0.18732728]]]

In [8]:
# 1.3.4 Задание
# Создать матрицу с 0 внутри, и 1 на границах.
import numpy as np
Z = np.ones((5,5), dtype=int)
Z[1:-1:,1:-1:] = 0
print(Z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

In [9]:
# 1.3.5 Задание
# Создать массив и отсортировать его в порядке убывания.
import numpy as np
Z = np.array(range(14))
Z.sort()
Z = Z[::-1]
print(Z)

[13 12 11 10  9  8  7  6  5  4  3  2  1  0]

In [10]:
# 1.3.6 Задание
# Создать матрицу 5x5 со случайными значениями.
# Вывести форму, размер и размерность матрицы.
import numpy as np
Z = np.random.random((5,5))
print("Форма матрицы:")
print(Z.shape)
print("Размер матрицы:")
print(Z.size)
print("Размерность матрицы:")
print(Z.ndim)

Форма матрицы:
(5, 5)
Размер матрицы:
25
Размерность матрицы:
2

In [15]:
# 2.3.1 Задание
# Задайте два Series, представляющих две точки в n-мерном пространстве.
# Найдите расстояние между ними.
import pandas as pd

print(sum((pd.Series([1, 2, 3, 4])-pd.Series([5, 6, 7, 8]))**2)**.5)

8.0

In [12]:
# 2.3.2 Задание
# Найдите в интернете любой csv файл и загрузите его в DataFrame.
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"

dataframe = pd.read_csv(url)
dataframe.head(5)

   year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

In [13]:
# 2.3.3 Задание
# Проделайте с получившимся из задания 2.3.2 DataFrame те же действия,
# что и в примерах 2.2.5-2.2.7.
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"

#Как в 2.2.5
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

#Как в 2.2.6
dataframe.iloc[1:4]

#Как в 2.2.7
dataframe[dataframe['name'] == 'Jennifer'].head(2)

       year      name gender  count
25     2000  Jennifer      F   9386
20489  2000  Jennifer      M     32

In [14]:
# 3.3.2 Задание
# Загрузить фрейм данных Iris.
# Выполните нормализацию первого признака (sepal_length_cm) с помощью MinMaxScaler
# и второго признака (sepal_width_cm) с помощью StandardScaler.
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)


scalerM = MinMaxScaler()
dataframe[['sepal_length_cm']] = scalerM.fit_transform(dataframe[['sepal_length_cm']])


scalerZ = StandardScaler()
dataframe[['sepal_width_cm']] = scalerZ.fit_transform(dataframe[['sepal_width_cm']])

dataframe

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,0.222222,1.032057,1.4,0.2,setosa
1,0.166667,-0.124958,1.4,0.2,setosa
2,0.111111,0.337848,1.3,0.2,setosa
3,0.083333,0.106445,1.5,0.2,setosa
4,0.194444,1.263460,1.4,0.2,setosa
...,...,...,...,...,...
145,0.666667,-0.124958,5.2,2.3,virginica
146,0.555556,-1.281972,5.0,1.9,virginica
147,0.611111,-0.124958,5.2,2.0,virginica
148,0.527778,0.800654,5.4,2.3,virginica
149,0.444444,-0.124958,5.1,1.8,virginica